version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: true
      - image: redis


    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          command: |
            sudo pip install pipenv
            pipenv install --dev
      - run:
          command: pipenv run "pytest --cov=./"
